# Generated by Django 3.2.6 on 2021-08-08 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, null=True, verbose_name='delete date')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, null=True, verbose_name='delete date')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('favourite', models.BooleanField(default=False, verbose_name='like product')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_time_stamp', models.DateTimeField(blank=True, null=True, verbose_name='delete date')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('province', models.CharField(max_length=50, verbose_name='province')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('postal_address', models.CharField(max_length=250, verbose_name='postal address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
