# Generated by Django 3.2.6 on 2021-08-17 13:05

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(help_text='put picture for product', upload_to=product.models.product_images_path, verbose_name='image'),
        ),
    ]
