# Generated by Django 3.2.6 on 2021-08-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='customer_allowed',
            field=models.ManyToManyField(help_text='customer allow to use this code ', to='customer.Customer', verbose_name='customer offcode'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='customer_use',
            field=models.BooleanField(default=False, help_text='if customer used '),
        ),
    ]
