# Generated by Django 3.2.6 on 2021-08-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('delivered', 'delivered'), ('cancled', 'cancled'), ('payed', 'payed')], help_text='enter the order status', max_length=50, verbose_name='status'),
        ),
    ]
